### PR TITLE
Agent-links.php file with nav button to GitHub repo.

### PR DESCRIPTION
**Pull request by precursorca**
Add a navbutton to the BlueSky Connect Github repo to make it easier to access the wiki.

### CODE REVIEW

**Comment by smaddock** [comment]
The images are for the Wiki I assume?

**Comment by sphen13** [comment]
looks like it - once in the repo the wiki page can be relinked.

**Comment by precursorca** [comment]
Yeah, I forgot about those. Thought I was able to edit the wiki directly once you made blueskyconnect.



---
Alex Narvey
***@***.***

**Comment by sphen13** [comment]
yes you are @precursorca - but the way that git handles images is by reference. it doesnt get put in the wiki directly - so in this case the images would be added/committed to repo and then we would change the image location in the wiki page.

**Pull request merged**
