### PR TITLE
Add curl for older OS

### PR DESCRIPTION
**Pull request by sphen13**
Bundle curl which support tls 1.2+ for older OS.

Tested with macOS 10.11+

### CODE REVIEW

**Comment by smaddock** [comment]
Oof. I like this better than allowing insecure connections, but oof.

**Comment by smaddock** [comment]
Although the current official WireGuard version requires 10.14+ :/

**Comment by smaddock** [comment]
Maybe we could use openssl/libressl’s built in `s_client` instead of `curl`… the calls done by the BlueSky client are fairly simple.

**Comment by sphen13** [comment]
As waiting for the shame comments :) was partially because I wanted a challenge but I agree not great. It does work and barely changes code. I am tempted as it works and we will clearly drop support before we switch to something else. Have not been able to test 10.10 yet. Fails on 10.9 due to system libraries. I am not great at trying to get this to compile statically but also have given too much effort towards this :)

I LOVE wireguard and use it all the time. We would still need to rely on TLS 1.2+ for that I would presume (server registration etc).

**Comment by smaddock** [comment]
Yeah I guess I was thinking down the road. And didn’t mean to shame. Since it’s only changing a handful of lines in bluesky.sh and helper.sh, it’s probably worth just going this route for 2.3.3. Sorry I didn’t test more on older OS’s! Would this close #36 ?

**Comment by sphen13** [comment]
Ha I kid with the shaming. I mean I'm shaming myself. Who uses these older OS? Yikes. But yes it would close that issue...

**Comment by smaddock** [comment]
Yeah playing around with s_client now, URL encoding the form values is probably not worth the extra effort. And TLS 1.2 was supposedly supported going back to 10.11, but I can’t get it to work on 10.12… it is working for me on 10.13 though.

**Comment by smaddock** [comment]
If this gets BlueSky working for 10.11 through 12.3.1 let’s merge it. We can be more diligent in the new-new version with options.

**Comment by smaddock** [comment]
Gah. Just realized it’s probably the CF libraries that work back to 10.11 🤦‍♂️

**Pull request merged**
